Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# Setting off false-positives :(
Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Naming:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Exclude:
    - 'lib/sqeduler/version.rb'
