Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics:
  Enabled: false

Naming:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Exclude:
    - 'lib/sqeduler/version.rb'

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false
