Lint/EndAlignment:
  AlignWith: variable

# Setting off false-positives :(
Lint/UnneededDisable:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 150

# just a really annoying check, especially when logging
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Exclude:
    - 'lib/sqeduler/version.rb'
